### PR TITLE
fix: properly restore nested wildcard values

### LINKED ISSUE #50: Original object is modified and not restored in any way
I want to be able the redact a key in multiple levels. So i wrote this code:

```js
const fastRedact = require('fast-redact');
const paths = ['*.d', '*.*.d', '*.*.*.d'];

const redact = fastRedact({
  paths,
});

const obj = {
  x: { c: { d: 'hide me', e: 'leave me be' } },
  y: { c: { d: 'and me', f: 'I want to live' } },
  z: { c: { d: 'and also I', g: 'I want to run in a stream' } },
};

console.log(redact(obj));
console.log(obj);
```

The output is:
```
{"x":{"c":{"d":"[REDACTED]","e":"leave me be"}},"y":{"c":{"d":"[REDACTED]","f":"I want to live"}},"z":{"c":{"d":"[REDACTED]","g":"I want to run in a stream"}}}
{
  x: { c: { d: '[REDACTED]', e: 'leave me be' } },
  y: { c: { d: '[REDACTED]', f: 'I want to live' } },
  z: { c: { d: '[REDACTED]', g: 'I want to run in a stream' } }
}
```

You can see that the original object is **modified**.

Seems like something is wrong with the [`nestedRestore`](https://github.com/davidmarkclements/fast-redact/blob/41339e6fa3e8b3a47c7266d3b5540ca0a8dd6764/lib/modifiers.js#L44) and the [`nestedRedact`](https://github.com/davidmarkclements/fast-redact/blob/41339e6fa3e8b3a47c7266d3b5540ca0a8dd6764/lib/modifiers.js#L65) functions.

When i added multiple levels that do not exist in the object. Seems like that `nestedRedact` with the `specialSet` functions doesn't build the store properly.

### PR DESCRIPTION
**Pull request by matt-clarson**
fixes #50 
also fixes https://github.com/pinojs/pino/issues/1745

This fixes the issue of restoring redacting values across multiple nested wildcards - the problem was that the redact/restore modifiers assumed the same value could be used to restore all instances of a redacted path. To fix, I've changed the `specialSet` function to keep track of the paths it visits in a tree, so that the correct path/value can be stored for use in restoring.

This has required a couple of extra modifications to the `specialSet` and `iterateNthLevel` functions:
- special set now doesn't return anything - it takes the store as an argument and pushes restore instructions to it directly
  - this also means that there's no need to return an `exists` value for paths that aren't being redacted - where that was being done we can just not update the store
- the `iterateNthLevel` function also doesn't returning anything now, similarly taking and mutating the store itself 
  - as far as i can tell, this change also fixed a separate bug where `iterateNthLevel` would exit early, leaving some parts of a wildcard path untouched - this is covered in a new test case

### CODE REVIEW

File: lib/modifiers.js [hunk 1]
```diff
@@ -42,27 +42,12 @@ function groupRedact (o, path, censor, isCensorFct, censorFctTakesPath) {
...
-          const tKey = targetKeys[j]
-          const subTarget = target[tKey]
-          if (has(subTarget, key)) {
-            subTarget[key] = value
-          }
-        }
-      }
-    } else {
-      restoreNthLevel(key, target, value, level)
+  for (const { parent, path, value } of arr) {
```
Comment (simoneb) [inline lib/modifiers.js:45]: you may want to consider comparing the performance of this approach to iteration with a plain for loop. I suspect that the motivation behind the for loop in the original code was indeed related to performance.

**Review by simoneb — COMMENTED** [review]
Very hard to make sense of what's going on here without intimate knowledge of this package, so I'll just comment for now.

I'm fairly confident that this package has extensive code coverage and therefore, if all tests pass in addition to the new ones, you fixed the issue without introducing any regression, but the package maintainer is probably the best person to confirm that.

Apart from this, excellent job, the code is quite cryptic and solving the issue without introducing regressions is a remarkable achievement.

File: lib/modifiers.js [hunk 2]
```diff
@@ -200,35 +195,66 @@ function iterateNthLevel (wcov, level, k, path, afterPath, censor, isCensorFct,
...
-    return
+function tree () {
+  return { parent: null, key: null, children: [], depth: 0 }
+}
+
+/**
+ * creates a new node in the tree, attaching it as a child of the provided parent node
+ * if the specified depth matches the parent depth, adds the new node as a _sibling_ of the parent instead
+ */
+function node (parent, key, depth) {
```
Comment (jsumners) [inline lib/modifiers.js:230]: Thank you for adding some jsdoc. Please complete it by adding the `@param` and `@returns` directives.

File: lib/modifiers.js [hunk 3]
```diff
@@ -200,35 +195,66 @@ function iterateNthLevel (wcov, level, k, path, afterPath, censor, isCensorFct,
...
+  parent.children.push(child)
+
+  return child
+}
+
+/**
+ * create a restore instruction for the given redactPath node
+ * generates a path in reverse order by walking up the redactPath tree
+ */
+function restoreInstr (node, value, parent) {
```
Comment (jsumners) [inline lib/modifiers.js:251]: Same as above.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
this is amazing work, thanks!
